apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ng-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  args:
    - --default-ssl-certificate
  tls:
  - hosts:
      - rippingresource.com
    secretName: "rippingresource-com-tls-acme"
  rules:
    - host: thenextchapter.pw
      http:
        paths:
          - backend:
              service:
                name: the-next-chapter-entrypoint
                port:
                  number: 80
            path: /
            pathType: Prefix

    - host: rippingresource.com
      http:
        paths:
          - backend:
              service:
                name: ripping-resource-entrypoint
                port:
                  number: 80
            path: /
            pathType: Prefix
